extends CharacterBody2D

signal jumped
signal fell
signal power_used
signal power_activated(id: String)
const Powers=preload("res://scripts/powers.gd")
var cooldowns: Dictionary={}
var effects: Dictionary={}
var extra_jump=false
var effect_time=0.0
var burn_seconds=0.0
var wet_seconds=0.0
const SPEED=82.0
const AUTO_SPEED=110.0
const GRAVITY=680.0
var fall_gravity_multiplier=1.0
var jump_time_scale=1.0
const JUMP_SPEED=-234.0
var sprite: AnimatedSprite2D
var character_id="joao_miguel"
var buffered_jump=0.0
var pending_sensor_jump=0.0
var coyote=0.0
var power_seconds=0.0
var has_power=false
var active=true
var button_input_enabled=true
var auto_run=false
var decision_zone=false
var sensor_jump=false
var land_seconds=0.0
var celebrate=false
var success_pending=false
var success_seconds=0.0
var animations_metadata: Dictionary={}

func configure_sensor_jump(enabled: bool):
 fall_gravity_multiplier=2.0 if enabled else 1.0
 jump_time_scale=1.5 if enabled else 1.0

func _ready():
 var shape=CollisionShape2D.new()
 var rect=RectangleShape2D.new();rect.size=Vector2(14,29)
 shape.shape=rect;shape.position=Vector2(0,-14.5)
 add_child(shape)
 collision_layer=2
 collision_mask=1
 floor_snap_length=4
 sprite=AnimatedSprite2D.new()
 sprite.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
 add_child(sprite)
 load_character(character_id)

func load_character(id: String):
 character_id=id
 var frames=SpriteFrames.new();frames.remove_animation("default")
 var data_path="res://art/animations.json"
 if FileAccess.file_exists(data_path):animations_metadata=JSON.parse_string(FileAccess.get_file_as_string(data_path))
 var info=animations_metadata.get(id,{})
 for action in ["idle","walk","run","jump","fall","land","celebrate"]:
  frames.add_animation(action)
  frames.set_animation_loop(action,action in ["idle","walk","run","fall","celebrate"])
  frames.set_animation_speed(action,12 if action=="run" else 8 if action=="walk" else 10 if action=="land" else 5)
  var clips=info.get(action,[])
  if clips.is_empty():continue
  for clip in clips:
   var atlas=AtlasTexture.new();atlas.atlas=load("res://art/"+clip.file)
   atlas.region=Rect2(clip.x,clip.y,clip.w,clip.h)
   # A fixed logical frame is generated by the texture margin, preserving foot pivot.
   # Texture cropping/alignment belongs to the runtime atlas; source PNG stays unchanged.
   frames.add_frame(action,atlas)
 sprite.sprite_frames=frames
 sprite.play("idle")
 sprite.frame_changed.connect(align_frame) if not sprite.frame_changed.is_connected(align_frame) else null
 align_frame()

func align_frame():
 var t=sprite.sprite_frames.get_frame_texture(sprite.animation,sprite.frame) if sprite.sprite_frames.get_frame_count(sprite.animation)>0 else null
 if t==null:return
 var clips=animations_metadata.get(character_id,{}).get(str(sprite.animation),[])
 var ref_height=float(clips[sprite.frame].get("scale_reference_height",t.get_height())) if sprite.frame<clips.size() else t.get_height()
 var scale_factor=34.0/ref_height
 sprite.scale=Vector2.ONE*scale_factor
 sprite.position=Vector2(0,-t.get_height()*scale_factor/2.0)

func clear_commands():
 buffered_jump=0
 pending_sensor_jump=0
 sensor_jump=false
 velocity=Vector2.ZERO
 coyote=0

func _physics_process(delta):
 if not active:return
 if celebrate:
  velocity.x=0
  animate("celebrate")
  return
 buffered_jump=maxf(0,buffered_jump-delta)
 pending_sensor_jump=maxf(0,pending_sensor_jump-delta)
 coyote=0.11 if is_on_floor() else maxf(0,coyote-delta)
 power_seconds=maxf(0,power_seconds-delta)
 land_seconds=maxf(0,land_seconds-delta)
 success_seconds=maxf(0,success_seconds-delta)
 if success_pending and is_on_floor():
  success_pending=false;success_seconds=1.4
 if button_input_enabled and Input.is_action_just_pressed("jump"):
  buffered_jump=0.13
 if sensor_jump:
  preload("res://scripts/sensor_diagnostics.gd").record("player_command",{"on_floor":is_on_floor(),"x":position.x,"y":position.y,"vy":velocity.y})
  # Keep one motion command through landing; the short keyboard buffer loses
  # a real movement when the child's timing differs from the animated jump.
  pending_sensor_jump=0.85
 sensor_jump=false
 for id in cooldowns:cooldowns[id]=maxf(0,float(cooldowns[id])-delta)
 for id in effects:effects[id]=maxf(0,float(effects[id])-delta)
 burn_seconds=maxf(0,burn_seconds-delta)
 wet_seconds=maxf(0,wet_seconds-delta)
 effect_time+=delta
 if button_input_enabled and Input.is_action_just_pressed("power"):activate_slot(0)
 if button_input_enabled and Input.is_action_just_pressed("power_two"):activate_slot(1)
 if is_on_floor():extra_jump=effect_active("double_jump")
 queue_redraw()
 var direction=1.0 if auto_run else (Input.get_axis("move_left","move_right") if button_input_enabled else 0.0)
 var speed=(AUTO_SPEED if auto_run else SPEED)*(1.65 if power_seconds>0 and not decision_zone else 1.0)
 if effect_active("slow") and is_on_floor():speed*=0.5
 velocity.x=move_toward(velocity.x,direction*speed,900*delta)
 if not is_on_floor():
  var gravity=GRAVITY*jump_time_scale*jump_time_scale*(fall_gravity_multiplier if velocity.y>0 else 1.0)
  velocity.y=minf(velocity.y+gravity*delta,390*jump_time_scale)
 if effect_active("wings") and velocity.y>35:velocity.y=35
 if effect_active("bubble"):
  velocity.y=clampf((100-position.y)*3.0,-70,35)
 if (buffered_jump>0 or pending_sensor_jump>0) and (coyote>0 or extra_jump):
  if coyote<=0:extra_jump=false
  velocity.y=JUMP_SPEED*jump_time_scale
  buffered_jump=0;pending_sensor_jump=0;coyote=0
  jumped.emit()
  preload("res://scripts/sensor_diagnostics.gd").record("player_jump",{"x":position.x,"y":position.y})
 var was_floor=is_on_floor()
 move_and_slide()
 if not was_floor and is_on_floor():
  land_seconds=0.22
  preload("res://scripts/sensor_diagnostics.gd").record("player_landed",{"x":position.x,"y":position.y})
 if absf(direction)>0.1:sprite.flip_h=direction<0
 if not is_on_floor():animate("jump" if velocity.y<0 else "fall")
 elif success_seconds>0 and absf(velocity.x)<=3:animate("celebrate")
 elif land_seconds>0:animate("land")
 elif absf(velocity.x)>3:animate("run" if auto_run or (power_seconds>0 and not decision_zone) else "walk")
 else:animate("idle")
 if position.y>240:
  fell.emit()

func effect_active(id: String) -> bool:
 return float(effects.get(id,0))>0

func activate_slot(slot: int) -> bool:
 if not active or celebrate or slot not in [0,1]:return false
 return activate_power(str(Data.equipped_powers()[slot]))

func activate_power(id: String) -> bool:
 var power=Powers.get_power(id)
 if not active or celebrate or power.is_empty() or float(cooldowns.get(id,0))>0:return false
 cooldowns[id]=float(power.duration)+float(power.recharge)
 effects[id]=float(power.duration)
 if id=="speed":
  power_seconds=float(power.duration);has_power=false;power_used.emit()
 elif id=="double_jump":
  extra_jump=is_on_floor()
  velocity.y=JUMP_SPEED*jump_time_scale;buffered_jump=0;coyote=0;jumped.emit()
 elif id=="wings":
  velocity.y=JUMP_SPEED*jump_time_scale;buffered_jump=0;coyote=0;jumped.emit()
 power_activated.emit(id)
 queue_redraw()
 return true

func _draw():
 if wet_seconds>0:
  for i in range(4):
   var offset=Vector2((i-1.5)*5,-1-absf(sin(effect_time*10+i))*4)
   draw_rect(Rect2(offset,Vector2(2,2)),Color("8de6f1"))
  draw_rect(Rect2(-7,-2,5,2),Color("57c4df"));draw_rect(Rect2(2,-2,5,2),Color("57c4df"))
 if burn_seconds>0:
  for i in range(3):
   var height=5+int(absf(sin(effect_time*12+i))*6)
   draw_rect(Rect2(-10+i*7,-height,5,height),Color("f37c36"))
   draw_rect(Rect2(-9+i*7,-height+3,3,height-3),Color("ffe185"))
 if effect_active("speed"):
  for i in range(4):draw_rect(Rect2(-18-i*6,-10-i%2*5,5,3),Color(1,0.75,0.25,0.8-i*0.15))
 if effect_active("wings"):
  for side in [-1,1]:
   for i in range(3):draw_rect(Rect2(side*(12+i*4)-3,-23+i*4,6,12-i*2),Color("dfceff"))
 if effect_active("bubble"):
  var points=PackedVector2Array()
  for i in range(17):points.append(Vector2(cos(i*TAU/16),sin(i*TAU/16))*26+Vector2(0,-17))
  draw_colored_polygon(points,Color(0.5,0.9,1,0.2));draw_polyline(points,Color("9af4ff"),2)
 for pair in [["magnet","ff91af"],["double_jump","a9e278"],["slow","92cca0"],["light","fff08a"]]:
  if effect_active(pair[0]):
   for i in range(4):
    var angle=effect_time*2+i*TAU/4
    draw_rect(Rect2(Vector2(cos(angle)*22,sin(angle)*20-17),Vector2(3,3)),Color(pair[1]))

func animate(action: String):
 if sprite.sprite_frames.get_frame_count(action)>0:
  sprite.play(action)
  align_frame()
